swagger: "2.0"
info:
  description: "RESTful API to manage web push notifications"
  version: "1.0.0"
  title: "Web Push Service"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "developersworkspace@gmail.com"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"
host: "your-domain.com"
basePath: "/api/v1"
schemes:
- "https"
- "http"
paths:
  /client:
    post:
      tags:
      - "Client"
      summary: "Create a client"
      description: "Obtain a key and a public key"
      operationId: "postClient"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Object containing endpoint"
        required: true
        schema:
          $ref: "#/definitions/ClientPostRequest"
      responses:
        400:
          description: "Invalid Request Body"
  /client/channels:
    get:
      tags:
      - "Client"
      summary: "Retrieve list of channels by client"
      description: ""
      operationId: "getClientChannels"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        401:
          description: "Unauthorized"
  /push/{channel}:
    post:
      tags:
      - "Push"
      summary: "Create a push notification"
      description: ""
      operationId: "postPushChannel"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - in: path
          name: channel
          schema:
            type: string
          required: true
          description: Channel Name
      responses:
        400:
          description: "Invalid Request Parameters"
        401:
          description: "Unauthorized"
  /subscription/{channel}:
    delete:
      tags:
      - "Subscription"
      summary: "Delete a subscription"
      description: ""
      operationId: "deleteSubscription"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - in: path
          name: channel
          schema:
            type: string
          required: true
          description: Channel Name
      responses:
        400:
          description: "Invalid Request Body/Parameters"
        401:
          description: "Unauthorized"
    post:
      tags:
      - "Subscription"
      summary: "Create a subscription"
      description: ""
      operationId: "postSubscription"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - in: path
          name: channel
          schema:
            type: string
          required: true
          description: Channel Name
      responses:
        400:
          description: "Invalid Request Body/Parameters"
        401:
          description: "Unauthorized"
securityDefinitions:
  Standard:
    type: "apiKey"
    name: "authorization"
    in: "header"
definitions:
  ClientPostRequest:
    type: "object"
    required:
    - "name"
    - "photoUrls"
    properties:
      endpoint:
        type: "string"
        example: "https://your-domain.com"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"